begin;

delete from public.sayless_round_results;
delete from public.sayless_draft_hands;
delete from public.sayless_draft_rejections;
delete from public.sayless_room_cards;
delete from public.sayless_cards;

insert into public.sayless_cards (title, description, points)
values
  ('Barbie', 'The pink doll icon behind the huge 2023 movie.', 1),
  ('Oppenheimer', 'The bomb biopic that opened opposite Barbie.', 1),
  ('Barbenheimer', 'The internet event of seeing Barbie and Oppenheimer together.', 1),
  ('Taylor Swift', 'Pop superstar behind the Eras Tour.', 1),
  ('Beyonce', 'Pop icon behind Renaissance and Cowboy Carter.', 1),
  ('Travis Kelce', 'NFL star who became tabloid royalty with Taylor Swift.', 1),
  ('Zendaya', 'Actor from Euphoria, Dune, and Spider-Man.', 1),
  ('Pedro Pascal', 'Internet favorite from The Last of Us and The Mandalorian.', 1),
  ('Timothee Chalamet', 'Actor from Dune and Wonka.', 1),
  ('Keanu Reeves', 'Beloved star of The Matrix and John Wick.', 1),
  ('Ryan Gosling', 'Actor who played Ken in Barbie.', 1),
  ('Margot Robbie', 'Actor and producer behind Barbie.', 1),
  ('Cillian Murphy', 'Actor who played Oppenheimer.', 1),
  ('Jenna Ortega', 'Actor known for Wednesday and Scream.', 1),
  ('Sabrina Carpenter', 'Pop singer behind Espresso.', 1),
  ('Chappell Roan', 'Pop singer with a giant recent breakout.', 2),
  ('Bad Bunny', 'Puerto Rican superstar rapper and singer.', 1),
  ('Dua Lipa', 'Pop singer behind Levitating and Houdini.', 1),
  ('Kendrick Lamar', 'Rapper behind Not Like Us.', 1),
  ('Drake', 'Mega-famous rapper and meme machine.', 1),
  ('Doge', 'The Shiba Inu meme with comic sans captions.', 1),
  ('Cheems', 'The other famous Shiba Inu meme dog.', 2),
  ('This Is Fine', 'The cartoon dog sitting calmly in a fire.', 1),
  ('Distracted Boyfriend', 'Stock photo meme about bad priorities.', 1),
  ('Woman Yelling at a Cat', 'Meme pairing a screaming woman with a confused white cat.', 1),
  ('Side-Eye Chloe', 'Little girl giving the camera a suspicious look.', 2),
  ('Blinking White Guy', 'Reaction meme of confused blinking disbelief.', 2),
  ('Success Kid', 'Baby with a fistful of sand and a victory face.', 2),
  ('Hide the Pain Harold', 'Smiling stock photo man with hidden suffering.', 2),
  ('Disaster Girl', 'Little girl smiling in front of a burning house.', 2),
  ('Keyboard Cat', 'Classic internet cat banging on a keyboard.', 2),
  ('Rickroll', 'Bait and switch using Never Gonna Give You Up.', 1),
  ('The Dress', 'Viral argument over blue and black or white and gold.', 1),
  ('Grimace Shake', 'Purple fast-food meme that turned into fake horror videos.', 2),
  ('Skibidi Toilet', 'Absurd internet series about singing toilet heads.', 2),
  ('Roman Empire Meme', 'Trend about how often men think about Rome.', 2),
  ('NPC Streamer', 'Livestream persona repeating canned reactions like a video game character.', 2),
  ('Area 51 Raid', 'The joke plan to storm Area 51 with Naruto runs.', 2),
  ('Ever Given', 'The ship that got stuck sideways in the Suez Canal.', 1),
  ('Will Smith Oscars Slap', 'The awards-show moment everyone immediately talked about.', 1),
  ('The Eras Tour', 'Taylor Swift stadium tour built around every album era.', 1),
  ('Renaissance World Tour', 'Beyonce tour with chrome horses and silver outfits.', 2),
  ('Brat', 'Lime-green Charli XCX album that became an internet aesthetic.', 2),
  ('Cowboy Carter', 'Beyonce album with a country pivot.', 2),
  ('Midnights', 'Taylor Swift album with Anti-Hero.', 1),
  ('Hamilton', 'Broadway smash about American history told through hip-hop.', 1),
  ('Bohemian Rhapsody', 'Queen song everyone sings dramatically.', 1),
  ('Mr. Brightside', 'The Killers song that refuses to die at parties.', 1),
  ('Hot to Go', 'Chappell Roan song with the arm dance.', 2),
  ('Espresso', 'Sabrina Carpenter song with the earworm chorus.', 1),
  ('Not Like Us', 'Kendrick Lamar diss track that took over the culture.', 1),
  ('Old Town Road', 'Lil Nas X smash that blurred rap and country.', 1),
  ('Gangnam Style', 'Global viral hit with the horse dance.', 1),
  ('Baby Shark', 'Childrens song that became unavoidable.', 1),
  ('Rebecca Black Friday', 'Infamous viral pop song from early YouTube.', 2),
  ('Daft Punk Helmets', 'The robot headgear from the electronic duo.', 2),
  ('Eurovision', 'International song contest full of camp and chaos.', 2),
  ('Coachella', 'Festival known for celebrity sightings and desert outfits.', 1),
  ('K-pop Lightstick', 'Custom glowing concert wand for a fandom.', 2),
  ('Tiny Desk Concert', 'The stripped-down performance series at an office desk.', 2),
  ('Darth Vader', 'Star Wars villain in black armor with heavy breathing.', 1),
  ('Grogu', 'The tiny green Force user many people still call Baby Yoda.', 1),
  ('The Mandalorian', 'Helmeted bounty hunter from Star Wars.', 1),
  ('Wednesday Addams', 'Deadpan goth schoolgirl from Wednesday.', 1),
  ('Eleven', 'Shaved-head psychic kid from Stranger Things.', 1),
  ('Walter White', 'Chemistry teacher turned drug kingpin.', 1),
  ('Saul Goodman', 'Strip-mall lawyer with a catchy name.', 1),
  ('Kendall Roy', 'Succession rich kid forever seeking approval.', 2),
  ('Ted Lasso', 'Mustached coach who leads with kindness.', 1),
  ('Fleabag', 'British antihero who talks to the camera.', 2),
  ('Michael Scott', 'The Office boss who thinks he is hilarious.', 1),
  ('Dwight Schrute', 'Beet farmer and assistant to the regional manager.', 1),
  ('Tony Soprano', 'Mob boss seeing a therapist in prestige TV.', 2),
  ('Don Draper', 'Ad man with a perfect suit and a secret past.', 2),
  ('Homelander', 'The terrifying smiling superhero from The Boys.', 2),
  ('The White Lotus', 'Vacation satire where rich people spiral.', 2),
  ('RuPaul', 'Drag superstar behind Drag Race.', 1),
  ('Love Island', 'Reality dating villa full of recouplings.', 2),
  ('Bluey', 'Australian cartoon dog beloved by adults and kids.', 1),
  ('SpongeBob SquarePants', 'Yellow sponge who lives in a pineapple.', 1),
  ('Shrek', 'Ogre who told everyone layers are important.', 1),
  ('Donkey', 'Fast-talking sidekick from Shrek.', 1),
  ('The Joker', 'Batman villain with clown makeup and chaos energy.', 1),
  ('Spider-Man', 'Web-slinging superhero from Queens.', 1),
  ('Thanos Snap', 'Marvel moment where half the universe disappears.', 1),
  ('Top Gun Maverick', 'Legacy sequel with jets and beach football.', 1),
  ('Maverick', 'Tom Cruise pilot who still ignores authority.', 1),
  ('John Wick', 'Hitman who started over a stolen car and a dead dog.', 1),
  ('The Matrix Red Pill', 'The choice to learn the hidden truth.', 2),
  ('Dune Sandworm', 'Giant desert creature that swallows spice harvesters.', 1),
  ('Princess Leia', 'Star Wars rebel leader with the iconic buns.', 1),
  ('Indiana Jones', 'Archaeologist with a whip and a fedora.', 1),
  ('Jack Sparrow', 'Pirate captain who staggers and schemes.', 1),
  ('Elsa', 'Frozen queen who sings and makes ice castles.', 1),
  ('Moana', 'Disney hero who sails beyond the reef.', 1),
  ('Encanto', 'Disney movie about a magical family in Colombia.', 1),
  ('Minions', 'Little yellow chaos creatures in overalls.', 1),
  ('Gru', 'Long-nosed supervillain who adopted three girls.', 1),
  ('Paddington', 'Polite bear with a blue coat and marmalade sandwiches.', 2),
  ('Deadpool', 'Wisecracking Marvel antihero who breaks the fourth wall.', 1),
  ('Wolverine', 'Mutant with claws and a healing factor.', 1),
  ('Batman', 'Brooding billionaire with gadgets and trauma.', 1),
  ('Superman', 'Invincible hero in a cape from Krypton.', 1),
  ('Wonder Woman', 'Amazon warrior with a lasso and bracelets.', 1),
  ('Black Panther', 'Marvel king of Wakanda in a vibranium suit.', 1),
  ('Iron Man', 'Genius billionaire in a flying metal suit.', 1),
  ('Captain America', 'Marvel hero with the shield.', 1),
  ('Thor', 'Marvel god with the hammer and lightning.', 1),
  ('Loki', 'Marvel trickster with a horned helmet.', 1),
  ('Groot', 'Walking tree who mostly says one sentence.', 1),
  ('Woody', 'Cowboy toy from Toy Story.', 1),
  ('Buzz Lightyear', 'Space ranger toy with delusions of grandeur.', 1),
  ('Lightning McQueen', 'Race car who says Ka-chow.', 1),
  ('Remy from Ratatouille', 'Rat chef hiding under a toque.', 2),
  ('Lord Voldemort', 'Bald dark wizard with no nose.', 1),
  ('Harry Potter', 'Boy wizard with the lightning scar.', 1),
  ('Hermione Granger', 'Smartest wizard in the room with a time-turner past.', 1),
  ('Pikachu', 'Electric Pokemon mascot with red cheeks.', 1),
  ('Mario', 'Nintendo plumber in a red hat.', 1),
  ('Luigi', 'Tall green brother who gets scared easily.', 1),
  ('Princess Peach', 'Nintendo princess often rescued but increasingly playable.', 1),
  ('Bowser', 'Spiky turtle king who kidnaps Peach.', 1),
  ('Link', 'Silent hero with a sword and green roots.', 1),
  ('Princess Zelda', 'Royal from Hyrule with wisdom and magic.', 2),
  ('Master Chief', 'Green-armored Halo supersoldier.', 2),
  ('Lara Croft', 'Tomb raider with twin pistols.', 2),
  ('Sonic the Hedgehog', 'Blue hedgehog who runs at impossible speed.', 1),
  ('Knuckles', 'Red echidna from Sonic who punches first.', 2),
  ('Crash Bandicoot', 'Orange marsupial who spins through crates.', 2),
  ('Kirby', 'Pink puffball who inhales enemies.', 1),
  ('Pac-Man', 'Yellow arcade circle chased by ghosts.', 1),
  ('Cloud Strife', 'Spiky-haired swordsman from Final Fantasy VII.', 3),
  ('Sephiroth', 'Long-haired Final Fantasy villain with a giant sword.', 3),
  ('Geralt of Rivia', 'White-haired monster hunter from The Witcher.', 2),
  ('Kratos', 'God of War antihero with ash-white skin.', 2),
  ('Ellie', 'Teen survivor from The Last of Us.', 2),
  ('Joel Miller', 'The gruff smuggler from The Last of Us.', 2),
  ('Aang', 'Last Airbender kid with arrow tattoos.', 2),
  ('Appa', 'Flying bison who answers to yip yip.', 2),
  ('Goku', 'Dragon Ball hero who always wants a stronger fight.', 1),
  ('Vegeta', 'Proud Dragon Ball prince with a giant ego.', 2),
  ('Naruto Uzumaki', 'Orange-clad ninja obsessed with becoming Hokage.', 1),
  ('Sailor Moon', 'Magical girl who fights evil by moonlight.', 2),
  ('Monkey D. Luffy', 'Rubber pirate hero chasing the One Piece.', 2),
  ('Totoro', 'Huge fluffy forest spirit from Studio Ghibli.', 2),
  ('No-Face', 'Masked spirit from Spirited Away.', 2),
  ('Ash Ketchum', 'Pokemon trainer who never seemed to age.', 1),
  ('Team Rocket', 'Pokemon villains forever blasting off again.', 2),
  ('Hello Kitty', 'Sanrio icon with a bow and no mouth.', 1),
  ('Hatsune Miku', 'Virtual pop idol with turquoise twin-tails.', 3),
  ('Among Us Crewmate', 'Little astronaut accused of being sus.', 1),
  ('Fall Guys Bean', 'Jellybean battle royale character.', 2),
  ('Fortnite Default Dance', 'The dance that escaped into real life.', 1),
  ('Minecraft Creeper', 'Green pixel monster that explodes behind you.', 1),
  ('Steve from Minecraft', 'Blocky player character with a pickaxe.', 1),
  ('Roblox Oof', 'Classic game sound effect turned meme.', 3),
  ('Tetris', 'Puzzle game of falling blocks.', 1),
  ('Wordle', 'Five-letter puzzle people post as colored squares.', 1),
  ('Queen Elizabeth II', 'Long-reigning British monarch whose death dominated world news.', 1),
  ('Coronation of King Charles', 'Royal ceremony with gold carriages and crowns.', 2),
  ('Fyre Festival', 'Luxury festival disaster with sad cheese sandwiches.', 1),
  ('GameStop Short Squeeze', 'Meme-stock frenzy from Reddit and Wall Street.', 2),
  ('Bitcoin', 'The original mainstream cryptocurrency.', 1),
  ('Bored Ape Yacht Club', 'NFT collection of cartoon apes.', 2),
  ('Twitter Becoming X', 'The rebrand that left many people still saying Twitter.', 1),
  ('Threads App', 'Meta attempt at a text-based social network.', 2),
  ('BeReal', 'Social app that prompts one unfiltered post a day.', 2),
  ('Duolingo Owl', 'Language app mascot famous for unhinged marketing.', 1),
  ('Stanley Cup Tumbler', 'Huge insulated cup turned status symbol.', 2),
  ('Vision Pro', 'Apples mixed-reality headset with the eye display.', 2),
  ('Tesla Cybertruck', 'Angular pickup that looks like low-poly sci-fi.', 2),
  ('ChatGPT', 'AI chatbot that exploded into mainstream conversation.', 1),
  ('Wikipedia Rabbit Hole', 'Starting with one article and emerging hours later.', 2),
  ('Borat', 'Sacha Baron Cohen character with a catchphrase and grey suit.', 2),
  ('McLovin', 'Fake Hawaii ID from Superbad.', 2),
  ('Nacho Libre', 'Luchador comedy starring Jack Black.', 3),
  ('Zoolander Blue Steel', 'Ridiculously serious male model stare.', 2),
  ('David S. Pumpkins', 'Tom Hanks Halloween sketch character with question marks.', 4),
  ('Hot Rod Pool Jump', 'Cult-comedy stunt featuring a heroic fall into a pool.', 4),
  ('The Lonely Island', 'Comedy music trio behind absurd digital shorts.', 3),
  ('Nyan Cat', 'Pixel cat with a Pop-Tart body flying through space.', 2),
  ('Homestar Runner', 'Flash-animation universe from the early internet.', 4),
  ('Strong Bad Email', 'Cartoon villain answering strange emails at a computer.', 4),
  ('Leeroy Jenkins', 'World of Warcraft charge that ruined the plan.', 3),
  ('Peanut Butter Jelly Time', 'Banana costume song from internet history.', 3),
  ('Chocolate Rain', 'Deep-voiced viral song from YouTube.', 3),
  ('Dramatic Chipmunk', 'Tiny animal turning with shocking intensity.', 3),
  ('Bad Luck Brian', 'Yearbook photo meme about cursed outcomes.', 2),
  ('Overly Attached Girlfriend', 'Wide-eyed parody character from a viral song video.', 3),
  ('Arthur Fist', 'Cartoon screenshot used for restrained anger.', 2),
  ('Salt Bae', 'Chef who became famous for sprinkling salt theatrically.', 2),
  ('Cash Me Ousside', 'Talk-show quote that became a viral catchphrase.', 3),
  ('Damn Daniel', 'Viral repeated compliment about white Vans.', 3),
  ('Bernie Sanders Mittens', 'Inauguration photo turned into endless edits.', 2),
  ('Nicole Kidman AMC Ad', 'The movie-theater monologue people recite ironically now.', 4),
  ('Left Shark', 'Backup dancer who clearly had his own choreography.', 3),
  ('Vine Boom', 'The bass hit sound effect used in absurd edits.', 3),
  ('Harlem Shake', 'Early 2010s viral video trend with sudden dance chaos.', 2),
  ('Corn Kid', 'Little boy who really loved corn in a viral interview.', 2),
  ('Charlie Bit My Finger', 'Early viral home video with two brothers on a couch.', 3);

commit;

notify pgrst, 'reload schema';
